artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/531756958975489460/51f0b1c0bfda4cbbbf82ffeb8b101932/artifacts
end_time: 1711057615771
entry_point_name: ''
experiment_id: '531756958975489460'
lifecycle_stage: active
run_id: 51f0b1c0bfda4cbbbf82ffeb8b101932
run_name: data_check
run_uuid: 51f0b1c0bfda4cbbbf82ffeb8b101932
source_name: ''
source_type: 4
source_version: ''
start_time: 1711057615734
status: 3
tags: []
user_id: mle-user
