artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/268ab5d53a284c69812ceac8a12495a3/artifacts
end_time: 1710707153642
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 268ab5d53a284c69812ceac8a12495a3
run_name: Default
run_uuid: 268ab5d53a284c69812ceac8a12495a3
source_name: ''
source_type: 4
source_version: ''
start_time: 1710707153615
status: 3
tags: []
user_id: mle-user
