artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/dfda1230e5c34069a89636c439a23bc1/artifacts
end_time: 1710852720270
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: dfda1230e5c34069a89636c439a23bc1
run_name: Default
run_uuid: dfda1230e5c34069a89636c439a23bc1
source_name: ''
source_type: 4
source_version: ''
start_time: 1710852720205
status: 3
tags: []
user_id: mle-user
