artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/b1e5b47d5b3748ab9ad99637fd32ed8c/artifacts
end_time: 1710707413098
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b1e5b47d5b3748ab9ad99637fd32ed8c
run_name: Default
run_uuid: b1e5b47d5b3748ab9ad99637fd32ed8c
source_name: ''
source_type: 4
source_version: ''
start_time: 1710707413048
status: 3
tags: []
user_id: mle-user
