artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/6b947a768ee34e0c992c4a2859252b43/artifacts
end_time: 1710707228787
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6b947a768ee34e0c992c4a2859252b43
run_name: Default
run_uuid: 6b947a768ee34e0c992c4a2859252b43
source_name: ''
source_type: 4
source_version: ''
start_time: 1710707228728
status: 3
tags: []
user_id: mle-user
