artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/f77be0bc19054519bfd96576847f78bd/artifacts
end_time: 1711057532271
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f77be0bc19054519bfd96576847f78bd
run_name: Default
run_uuid: f77be0bc19054519bfd96576847f78bd
source_name: ''
source_type: 4
source_version: ''
start_time: 1711057532085
status: 3
tags: []
user_id: mle-user
